version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/postgresql  # Mount the directory with the SQL file
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh  # Mount the init script
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    entrypoint:
      - /bin/bash
      - -c
      - |
        chmod +x /docker-entrypoint-initdb.d/init.sh && /docker-entrypoint-initdb.d/init.sh


networks:
  my_network:

volumes:
  postgres_data:
