name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.tag.outputs.value }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Store git tag value to output
        id: tag
        run: echo "value=$(git describe --tags --always --abbrev=7)" >> $GITHUB_OUTPUT